id = "cinnamonwine-theme"
name = "cinnamon wine"
description = "A cinnamon-y, fall-inspired color scheme. Tries to harken back to the DEC VT320 aesthetic. Based on cinnamonwine.nvim"
version = "1.0.0"
schema_version = 1
authors = ["shoenot"]
repository = "https://github.com/shoenot/cinnamonwine.zed"
